const atividadesPortugues2ano = [
    { nome: "Ações no Texto", slug: "acoes-texto-2ano" },
    { nome: "Adjetivos", slug: "adjetivos-2ano" },
    { nome: "Artigos", slug: "artigos-2ano" },
    { nome: "Consciência Fonológica", slug: "consciencia-fonologica-2ano" },
    { nome: "Escrita e Coerência", slug: "escrita-e-coerencia-2ano" },
    { nome: "Escuta de Instruções", slug: "escuta-instrucoes-2ano" },
    { nome: "Espaço entre Palavras", slug: "espaco-entre-palavras-2ano" },
    { nome: "Fonemas Parecidos", slug: "fonemas-parecidos-2ano" },
    { nome: "Grafia Correta", slug: "grafia-correta-2ano" },
    { nome: "Leitura e Fluência", slug: "leitura-fluencia-2ano" },
    { nome: "Lugar e Tempo no Texto", slug: "lugar-tempo-texto-2ano" },
    { nome: "Ortografia C e S", slug: "ortografia-c-s-2ano" },
    { nome: "Ortografia R e RR", slug: "ortografia-r-rr-2ano" },
    { nome: "Ortografia S e SS", slug: "ortografia-s-ss-2ano" },
    { nome: "Personagens do Texto", slug: "personagens-texto-2ano" },
    { nome: "Pontuação e Maiúsculas", slug: "pontuacao-e-maiusculas-2ano" },
    { nome: "Recontar História", slug: "recontar-historia-2ano" },
    { nome: "Responder ao Ouvir", slug: "responder-ouvir-2ano" },
    { nome: "Rimas e Sons", slug: "rimas-e-sons-2ano" },
    { nome: "Sons e Variações", slug: "sons-e-variacoes-2ano" },
    { nome: "Substantivos", slug: "substantivos-2ano" },
    { nome: "Texto a partir de Imagem", slug: "texto-imagem-2ano" },
    { nome: "Vogais e Consoantes", slug: "vogais-e-consoantes-2ano" }
];