const atividadesMatematica1ano = [
    { nome: "Adição Animais", slug: "adicao-animais" },
    { nome: "Adição Brinquedos", slug: "adicao-brinquedos" },
    { nome: "Adição Simples", slug: "adicao-simples" },
    { nome: "Comparacao De Números", slug: "comparacao-de-numeros" },
    { nome: "Contagem E Grupos", slug: "contagem-e-grupos" },
    { nome: "Decomposicao Simples", slug: "decomposicao-simples" },
    { nome: "Formas", slug: "formas" },
    { nome: "Formas Geométricas Basicas", slug: "formas-geometricas-basicas" },
    { nome: "Grafico E Contagem", slug: "grafico-e-contagem" },
    { nome: "Graficos Simples", slug: "graficos-simples" },
    { nome: "Jogos E Desafios Logicos", slug: "jogos-e-desafios-logicos" },
    { nome: "Massa E Capacidade", slug: "massa-e-capacidade" },
    { nome: "Matemática 1 A 10", slug: "matematica-1-a-10" },
    { nome: "Medidas E Comparacao", slug: "medidas-e-comparacao" },
    { nome: "Nocoes De Espaco", slug: "nocoes-de-espaco" },
    { nome: "Nocoes De Quantidade", slug: "nocoes-de-quantidade" },
    { nome: "Nocoes De Tempo", slug: "nocoes-de-tempo" },
    { nome: "Nosso Dinheiro", slug: "nosso-dinheiro" },
    { nome: "Números Simples 1 A 5", slug: "numeros-simples-1-a-5" },
    { nome: "Números Simples 6 A 9", slug: "numeros-simples-6-a-9" },
    { nome: "Ordem Crescente E Decrescente", slug: "ordem-crescente-e-decrescente" },
    { nome: "Raciocinio Logico Problemas", slug: "raciocinio-logico-problemas" },
    { nome: "Reconhecimento Par Impar", slug: "reconhecimento-par-impar" },
    { nome: "Sequência Numerica", slug: "sequencia-numerica" },
    { nome: "Sequências E Padroes", slug: "sequencias-e-padroes" },
    { nome: "Simetria Simples", slug: "simetria-simples" },
    { nome: "Subtração", slug: "subtracao" },
    { nome: "Sucessor Antecessor", slug: "sucessor-antecessor" },
    { nome: "Unidade E Dezena", slug: "unidade-e-dezena" }
];
