const atividadesPortugues1ano = [
    { nome: "Artigos simples", slug: "artigos-simples" },
    { nome: "Atividade letra B", slug: "atividade-letra-B" },
    { nome: "Autoditado simples", slug: "autoditado-simples" },
    { nome: "Compreensao de textos", slug: "compreensao-de-textos" },
    { nome: "Consoantes", slug: "consoantes" },
    { nome: "Construcao de frases", slug: "construcao-de-frases" },
    { nome: "Formacao de palavras", slug: "formacao-de-palavras" },
    { nome: "Instrucoes simples", slug: "instrucoes-simples" },
    { nome: "Letras Maiúsculas (Início/Próprios)", slug: "letras-maiusculas-uso" },
    { nome: "Maiúsculas e Minúsculas", slug: "maiusculas-e-minusculas" },
    { nome: "Maiusculas e minusculas 2", slug: "maiusculas-e-minusculas 2" },
    { nome: "Nomear e ligar", slug: "nomear-e-ligar" },
    { nome: "Palavras do cotidiano", slug: "palavras-do-cotidiano" },
    { nome: "Palavras familiares", slug: "palavras-familiares" },
    { nome: "Ponto final e interrogacao", slug: "ponto-final-e-interrogacao" },
    { nome: "Pronomes pessoais", slug: "pronomes-pessoais" },
    { nome: "Rimas", slug: "rimas" },
    { nome: "Rimas e aliteracao", slug: "rimas-e-aliteracao" },
    { nome: "Silabas com B", slug: "silabas-com-b" },
    { nome: "Silabas com C", slug: "silabas-com-c" },
    { nome: "Silabas com D", slug: "silabas-com-d" },
    { nome: "Silabas com F", slug: "silabas-com-f" },
    { nome: "Silabas com G", slug: "silabas-com-g" },
    { nome: "Silabas com L", slug: "silabas-com-l" },
    { nome: "Silabas com M", slug: "silabas-com-m" },
    { nome: "Silabas com N", slug: "silabas-com-n" },
    { nome: "Silabas com P", slug: "silabas-com-p" },
    { nome: "Silabas com R", slug: "silabas-com-r" },
    { nome: "Silabas com S", slug: "silabas-com-s" },
    { nome: "Silabas com T", slug: "silabas-com-t" },
    { nome: "Silabas com V", slug: "silabas-com-v" },
    { nome: "Sons e silabas", slug: "sons-e-silabas" },
    { nome: "Sons finais", slug: "sons-finais" },
    { nome: "Sons iniciais", slug: "sons-iniciais" },
    { nome: "Substantivos e verbos", slug: "substantivos-e-verbos" },
    { nome: "Treino de Escrita", slug: "treino-escrita" },
    { nome: "Alfabeto: Vogais", slug: "vogais" },
    { nome: "Vogais 2", slug: "vogais 2" },
    { nome: "Vogais2", slug: "vogais2" }
];
