const atividadesMatematica1ano = [
    { nome: "Adição Simples", slug: "adicao-simples" },
    { nome: "Subtração", slug: "subtracao" },
    { nome: "Unidade e Dezena", slug: "unidade-e-dezena" },
    { nome: "Sequência Numérica", slug: "sequencia-numerica" },
    { nome: "Sequências e Padrões", slug: "sequencias-e-padroes" },
    { nome: "Comparação de Números", slug: "comparacao-de-numeros" },
    { nome: "Contagem e Grupos", slug: "contagem-e-grupos" },
    { nome: "Decomposição Simples", slug: "decomposicao-simples" },
    { nome: "Formas Geométricas Básicas", slug: "formas-geometricas-basicas" },
    { nome: "Formas", slug: "formas" },
    { nome: "Gráfico e Contagem", slug: "grafico-e-contagem" },
    { nome: "Gráficos Simples", slug: "graficos-simples" },
    { nome: "Jogos e Desafios Lógicos", slug: "jogos-e-desafios-logicos" },
    { nome: "Massa e Capacidade", slug: "massa-e-capacidade" },
    { nome: "Matemática 1 a 10", slug: "matematica-1-a-10" },
    { nome: "Medidas e Comparação", slug: "medidas-e-comparacao" },
    { nome: "Noções de Espaço", slug: "nocoes-de-espaco" },
    { nome: "Noções de Quantidade", slug: "nocoes-de-quantidade" },
    { nome: "Noções de Tempo", slug: "nocoes-de-tempo" },
    { nome: "Nosso Dinheiro", slug: "nosso-dinheiro" },
    { nome: "Números Simples 1 a 5", slug: "numeros-simples-1-a-5" },
    { nome: "Números Simples 6 a 9", slug: "numeros-simples-6-a-9" },
    { nome: "Ordem Crescente e Decrescente", slug: "ordem-crescente-e-decrescente" },
    { nome: "Raciocínio Lógico Problemas", slug: "raciocinio-logico-problemas" },
    { nome: "Reconhecimento Par Ímpar", slug: "reconhecimento-par-impar" },
    { nome: "Simetria Simples", slug: "simetria-simples" },
    { nome: "Sucessor Antecessor", slug: "sucessor-antecessor" }
];