const atividadesMatematica1ano = [
    { nome: "Adição Animais", slug: "adicao-animais" },
    { nome: "Adição Brinquedos", slug: "adicao-brinquedos" },
    { nome: "Adição Desenhos", slug: "adicao-desenhos" },
    { nome: "Adição Simples", slug: "adicao-simples" },
    { nome: "Comparacao De Números", slug: "comparacao-de-numeros" },
    { nome: "Contagem Comparacao 1 Ano", slug: "contagem-comparacao-1-ano" },
    { nome: "Contagem E Grupos", slug: "contagem-e-grupos" },
    { nome: "Contagem E Soma 1 Ano", slug: "contagem-e-soma-1-ano" },
    { nome: "Contagem Subtração 1 Ano", slug: "contagem-subtracao-1-ano" },
    { nome: "Decomposicao Simples", slug: "decomposicao-simples" },
    { nome: "Dezenas_unidades", slug: "dezenas_unidades" },
    { nome: "Exercicio 2  Adição Subtração 1 Ano", slug: "exercicio 2 -adicao-subtracao-1-ano" },
    { nome: "Exercicio Adição 1 Ano", slug: "exercicio-adicao-1-ano" },
    { nome: "Exercicio Adição Frutas 1 Ano", slug: "exercicio-adicao-frutas-1-ano" },
    { nome: "Exercicio Adição Subtração 1 Ano", slug: "exercicio-adicao-subtracao-1-ano" },
    { nome: "Exercicio Subtração 1 Ano", slug: "exercicio-subtracao-1-ano" },
    { nome: "Exercicio Subtração Frutas 1 Ano", slug: "exercicio-subtracao-frutas-1-ano" },
    { nome: "Formas", slug: "formas" },
    { nome: "Formas Cores", slug: "formas-cores" },
    { nome: "Formas Geométricas Basicas", slug: "formas-geometricas-basicas" },
    { nome: "Grafico E Contagem", slug: "grafico-e-contagem" },
    { nome: "Graficos", slug: "graficos" },
    { nome: "Graficos Simples", slug: "graficos-simples" },
    { nome: "Jogos E Desafios Logicos", slug: "jogos-e-desafios-logicos" },
    { nome: "Massa E Capacidade", slug: "massa-e-capacidade" },
    { nome: "Matemática 1 A 10", slug: "matematica-1-a-10" },
    { nome: "Medidas E Comparacao", slug: "medidas-e-comparacao" },
    { nome: "Medidas E Comparacao 1 Ano", slug: "medidas-e-comparacao-1-ano" },
    { nome: "Medidas Tempo", slug: "medidas-tempo" },
    { nome: "Nocoes De Espaco", slug: "nocoes-de-espaco" },
    { nome: "Nocoes De Quantidade", slug: "nocoes-de-quantidade" },
    { nome: "Nocoes De Tempo", slug: "nocoes-de-tempo" },
    { nome: "Nosso Dinheiro", slug: "nosso-dinheiro" },
    { nome: "Números Simples 1 A 5", slug: "numeros-simples-1-a-5" },
    { nome: "Números Simples 6 A 9", slug: "numeros-simples-6-a-9" },
    { nome: "Ordem Crescente E Decrescente", slug: "ordem-crescente-e-decrescente" },
    { nome: "Problemas Simples", slug: "problemas-simples" },
    { nome: "Raciocinio Logico Problemas", slug: "raciocinio-logico-problemas" },
    { nome: "Reconhecimento Par Impar", slug: "reconhecimento-par-impar" },
    { nome: "Sequência Numerica", slug: "sequencia-numerica" },
    { nome: "Sequência Numerica 2", slug: "sequencia-numerica-2" },
    { nome: "Sequências E Padroes", slug: "sequencias-e-padroes" },
    { nome: "Simetria Simples", slug: "simetria-simples" },
    { nome: "Sistema Monetario 1 Ano", slug: "sistema-monetario-1-ano" },
    { nome: "Subtração", slug: "subtracao" },
    { nome: "Subtração Desenhos", slug: "subtracao-desenhos" },
    { nome: "Sucessor Antecessor", slug: "sucessor-antecessor" },
    { nome: "Unidade E Dezena", slug: "unidade-e-dezena" }
];
