const atividadesPortugues1ano = [
    { nome: "Alfabeto: Vogais", slug: "vogais" },
    { nome: "Silabas com B", slug: "silabas-com-b" },
    { nome: "Silabas com D", slug: "silabas-com-d" },
    { nome: "Silabas com F", slug: "silabas-com-f" },
    { nome: "Silabas com G", slug: "silabas-com-g" },
    { nome: "Silabas com L", slug: "silabas-com-l" },
    { nome: "Silabas com M", slug: "silabas-com-m" },
    { nome: "Silabas com N", slug: "silabas-com-n" },
    { nome: "Silabas com P", slug: "silabas-com-p" },
    { nome: "Silabas com R", slug: "silabas-com-r" },
    { nome: "Silabas com T", slug: "silabas-com-t" },
    { nome: "Silabas com V", slug: "silabas-com-v" },
    { nome: "Sons e Sílabas", slug: "sons-e-silabas" },
    { nome: "Rimas e Aliteração", slug: "rimas-e-aliteracao" },
    { nome: "Substantivos e Verbos", slug: "substantivos-e-verbos" },
    { nome: "Artigos Simples", slug: "artigos-simples" },
    { nome: "Pronomes Pessoais", slug: "pronomes-pessoais" },
    { nome: "Ponto Final e Interrogação", slug: "ponto-final-e-interrogacao" },
    { nome: "Letras Maiúsculas (Início/Próprios)", slug: "letras-maiusculas-uso" },
    { nome: "Maiúsculas e Minúsculas", slug: "maiusculas-e-minusculas" },
    { nome: "Palavras do Cotidiano", slug: "palavras-do-cotidiano" },
    { nome: "Palavras Familiares", slug: "palavras-familiares" },
    { nome: "Instruções Simples", slug: "instrucoes-simples" },
    { nome: "Compreensão de Textos", slug: "compreensao-de-textos" },
    { nome: "Construção de Frases", slug: "construcao-de-frases" },
    { nome: "Formação de Palavras", slug: "formacao-de-palavras" },
    { nome: "Nomear e Ligar", slug: "nomear-e-ligar" },
    { nome: "Autoditado Simples", slug: "autoditado-simples" },
    { nome: "Treino de Escrita", slug: "treino-escrita" }
];