const atividadesPortugues1ano = [
    { nome: "Artigos Simples", slug: "artigos-simples" },
    { nome: "Atividade Letra B", slug: "atividade-letra-B" },
    { nome: "Autoditado Simples", slug: "autoditado-simples" },
    { nome: "Compreensão De Textos", slug: "compreensao-de-textos" },
    { nome: "Consoantes", slug: "consoantes" },
    { nome: "Construção De Frases", slug: "construcao-de-frases" },
    { nome: "Formação De Palavras", slug: "formacao-de-palavras" },
    { nome: "Instruções Simples", slug: "instrucoes-simples" },
    { nome: "Letras Maiúsculas (Início/Próprios)", slug: "letras-maiusculas-uso" },
    { nome: "Maiúsculas e Minúsculas", slug: "maiusculas-e-minusculas" },
    { nome: "Maiúsculas E Minúsculas 2", slug: "maiusculas-e-minusculas 2" },
    { nome: "Nomear E Ligar", slug: "nomear-e-ligar" },
    { nome: "Palavras Do Cotidiano", slug: "palavras-do-cotidiano" },
    { nome: "Palavras Familiares", slug: "palavras-familiares" },
    { nome: "Ponto Final E Interrogação", slug: "ponto-final-e-interrogacao" },
    { nome: "Pronomes Pessoais", slug: "pronomes-pessoais" },
    { nome: "Rimas", slug: "rimas" },
    { nome: "Rimas E Aliteração", slug: "rimas-e-aliteracao" },
    { nome: "Sílabas Com B", slug: "silabas-com-b" },
    { nome: "Sílabas Com C", slug: "silabas-com-c" },
    { nome: "Sílabas Com D", slug: "silabas-com-d" },
    { nome: "Sílabas Com F", slug: "silabas-com-f" },
    { nome: "Sílabas Com G", slug: "silabas-com-g" },
    { nome: "Sílabas Com L", slug: "silabas-com-l" },
    { nome: "Sílabas Com M", slug: "silabas-com-m" },
    { nome: "Sílabas Com N", slug: "silabas-com-n" },
    { nome: "Sílabas Com P", slug: "silabas-com-p" },
    { nome: "Sílabas Com R", slug: "silabas-com-r" },
    { nome: "Sílabas Com S", slug: "silabas-com-s" },
    { nome: "Sílabas Com T", slug: "silabas-com-t" },
    { nome: "Sílabas Com V", slug: "silabas-com-v" },
    { nome: "Sons E Sílabas", slug: "sons-e-silabas" },
    { nome: "Sons Finais", slug: "sons-finais" },
    { nome: "Sons Iniciais", slug: "sons-iniciais" },
    { nome: "Substantivos E Verbos", slug: "substantivos-e-verbos" },
    { nome: "Treino de Escrita", slug: "treino-escrita" },
    { nome: "Alfabeto: Vogais", slug: "vogais" },
    { nome: "Vogais 2", slug: "vogais 2" },
    { nome: "Vogais2", slug: "vogais2" }
];
