const atividadesPortugues2ano = [
    { nome: "Acoes texto 2ano", slug: "acoes-texto-2ano" },
    { nome: "Adjetivos 2ano", slug: "adjetivos-2ano" },
    { nome: "Artigos 2ano", slug: "artigos-2ano" },
    { nome: "Consciencia fonologica 2ano", slug: "consciencia-fonologica-2ano" },
    { nome: "Escrita e coerencia 2ano", slug: "escrita-e-coerencia-2ano" },
    { nome: "Escuta instrucoes 2ano", slug: "escuta-instrucoes-2ano" },
    { nome: "Espaco entre palavras 2ano", slug: "espaco-entre-palavras-2ano" },
    { nome: "Fonemas parecidos 2ano", slug: "fonemas-parecidos-2ano" },
    { nome: "Grafia correta 2ano", slug: "grafia-correta-2ano" },
    { nome: "Leitura fluencia 2ano", slug: "leitura-fluencia-2ano" },
    { nome: "Lugar tempo texto 2ano", slug: "lugar-tempo-texto-2ano" },
    { nome: "Ortografia c s 2ano", slug: "ortografia-c-s-2ano" },
    { nome: "Ortografia r rr 2ano", slug: "ortografia-r-rr-2ano" },
    { nome: "Ortografia s ss 2ano", slug: "ortografia-s-ss-2ano" },
    { nome: "Palavras p b", slug: "palavras-p-b" },
    { nome: "Palavras ss cedilha", slug: "palavras-ss-cedilha" },
    { nome: "Palavras t d", slug: "palavras-t-d" },
    { nome: "Palavras x ch", slug: "palavras-x-ch" },
    { nome: "Personagens texto 2ano", slug: "personagens-texto-2ano" },
    { nome: "Pontuacao e maiusculas 2ano", slug: "pontuacao-e-maiusculas-2ano" },
    { nome: "Recontar historia 2ano", slug: "recontar-historia-2ano" },
    { nome: "Responder ouvir 2ano", slug: "responder-ouvir-2ano" },
    { nome: "Rimas e sons 2ano", slug: "rimas-e-sons-2ano" },
    { nome: "Sons e variacoes 2ano", slug: "sons-e-variacoes-2ano" },
    { nome: "Substantivos 2ano", slug: "substantivos-2ano" },
    { nome: "Texto imagem 2ano", slug: "texto-imagem-2ano" },
    { nome: "Vogais e consoantes 2ano", slug: "vogais-e-consoantes-2ano" }
];
