const atividadesMatematica2ano = [
    { nome: "Antecessor E Sucessor 2ano", slug: "antecessor-e-sucessor-2ano" },
    { nome: "Antecessor E Sucessor 2ano 2", slug: "antecessor-e-sucessor-2ano-2" },
    { nome: "Comparacao Comprimento 2ano", slug: "comparacao-comprimento-2ano" },
    { nome: "Comparar E Ordenar 2ano", slug: "comparar-e-ordenar-2ano" },
    { nome: "Comparar Quantidades 2ano", slug: "comparar-quantidades-2ano" },
    { nome: "Divisao Reparticao Igual 2ano", slug: "divisao-reparticao-igual-2ano" },
    { nome: "Estrategias De Contagem", slug: "estrategias-de-contagem" },
    { nome: "Figuras Planas 2ano", slug: "figuras-planas-2ano" },
    { nome: "Graficos E Tabelas 2ano", slug: "graficos-e-tabelas-2ano" },
    { nome: "Horas E Meia Hora", slug: "horas-e-meia-hora" },
    { nome: "Introducao Ao Dinheiro 2ano", slug: "introducao-ao-dinheiro-2ano" },
    { nome: "Introducao As Fracoes 2ano", slug: "introducao-as-fracoes-2ano" },
    { nome: "Introducao Multiplicacao Divisao", slug: "introducao-multiplicacao-divisao" },
    { nome: "Medidas Basicas 2ano", slug: "medidas-basicas-2ano" },
    { nome: "Números 101 A 200", slug: "numeros-101-a-200" },
    { nome: "Números Ate 100", slug: "numeros-ate-100" },
    { nome: "Operacoes Problemas 2ano", slug: "operacoes-problemas-2ano" },
    { nome: "Posicao E Espaco 2ano", slug: "posicao-e-espaco-2ano" },
    { nome: "Problemas Simples 2ano", slug: "problemas-simples-2ano" },
    { nome: "Problemas Soma", slug: "problemas-soma" },
    { nome: "Problemas Subtração 2ano", slug: "problemas-subtracao-2ano" },
    { nome: "Sequências Multiplas", slug: "sequencias-multiplas" },
    { nome: "Soma 2 Ano", slug: "soma-2-ano" },
    { nome: "Subtração 2 Ano", slug: "subtracao-2-ano" }
];
