const atividadesPortugues2ano = [
    { nome: "Ações Texto 2º Ano", slug: "acoes-texto-2ano" },
    { nome: "Adjetivos 2º Ano", slug: "adjetivos-2ano" },
    { nome: "Artigos 2º Ano", slug: "artigos-2ano" },
    { nome: "Atividade Portugues Chapeuzinho 2º Ano", slug: "atividade-portugues-chapeuzinho-2-ano" },
    { nome: "Baú Das Rimas", slug: "bau-das-rimas" },
    { nome: "Consciência Fonológica 2º Ano", slug: "consciencia-fonologica-2ano" },
    { nome: "Escrita E Coerência 2º Ano", slug: "escrita-e-coerencia-2ano" },
    { nome: "Escuta Instruções 2º Ano", slug: "escuta-instrucoes-2ano" },
    { nome: "Espaço Entre Palavras 2º Ano", slug: "espaco-entre-palavras-2ano" },
    { nome: "Fábrica De Sílabas", slug: "fabrica-de-silabas" },
    { nome: "Fonemas Parecidos 2º Ano", slug: "fonemas-parecidos-2ano" },
    { nome: "Grafia Correta 2º Ano", slug: "grafia-correta-2ano" },
    { nome: "Leitura Fluência 2º Ano", slug: "leitura-fluencia-2ano" },
    { nome: "Leitura Interpretação Frases", slug: "leitura-intepretacao-frases" },
    { nome: "Lugar Tempo Texto 2º Ano", slug: "lugar-tempo-texto-2ano" },
    { nome: "Ortografia C S 2º Ano", slug: "ortografia-c-s-2ano" },
    { nome: "Ortografia R Rr 2º Ano", slug: "ortografia-r-rr-2ano" },
    { nome: "Ortografia S Ss 2º Ano", slug: "ortografia-s-ss-2ano" },
    { nome: "Palavras Com B 2º Ano", slug: "palavras-com-b-2-ano" },
    { nome: "Palavras P B", slug: "palavras-p-b" },
    { nome: "Palavras Ss Cedilha", slug: "palavras-ss-cedilha" },
    { nome: "Palavras T D", slug: "palavras-t-d" },
    { nome: "Palavras X Ch", slug: "palavras-x-ch" },
    { nome: "Personagens Texto 2º Ano", slug: "personagens-texto-2ano" },
    { nome: "Pontuação E Maiúsculas 2º Ano", slug: "pontuacao-e-maiusculas-2ano" },
    { nome: "Recontar História 2º Ano", slug: "recontar-historia-2ano" },
    { nome: "Responder Ouvir 2º Ano", slug: "responder-ouvir-2ano" },
    { nome: "Rimas E Sons 2º Ano", slug: "rimas-e-sons-2ano" },
    { nome: "Sílabas Finais 2º Ano", slug: "silabas-finais-2-ano" },
    { nome: "Sílabas Iniciais 2º Ano", slug: "silabas-iniciais-2-ano" },
    { nome: "Sons E Variações 2º Ano", slug: "sons-e-variacoes-2ano" },
    { nome: "Substantivos 2º Ano", slug: "substantivos-2ano" },
    { nome: "Texto Imagem 2º Ano", slug: "texto-imagem-2ano" },
    { nome: "Trem Do Alfabeto", slug: "trem-do-alfabeto" },
    { nome: "Vogais E Consoantes 2º Ano", slug: "vogais-e-consoantes-2ano" }
];
