const atividadesMatematica2ano = [
    { nome: "Antecessor E Sucessor 2º Ano", slug: "antecessor-e-sucessor-2ano" },
    { nome: "Antecessor E Sucessor 2º Ano 2", slug: "antecessor-e-sucessor-2ano-2" },
    { nome: "Atividade Figuras Planas 2º Ano", slug: "atividade-figuras-planas-2-ano" },
    { nome: "Atividade Ordem Numerica 2º Ano", slug: "atividade-ordem-numerica-2-ano" },
    { nome: "Atividades De Subtração 2º Ano", slug: "atividades-de-subtração-2-ano" },
    { nome: "Comparação Comprimento 2º Ano", slug: "comparacao-comprimento-2ano" },
    { nome: "Comparar E Ordenar 2º Ano", slug: "comparar-e-ordenar-2ano" },
    { nome: "Comparar Quantidades 2º Ano", slug: "comparar-quantidades-2ano" },
    { nome: "Dezenas Unidades", slug: "dezenas-unidades" },
    { nome: "Divisão Repartição Igual 2º Ano", slug: "divisao-reparticao-igual-2ano" },
    { nome: "Enigma Das Operações", slug: "enigma-das-operacoes" },
    { nome: "Estratégias De Contagem", slug: "estrategias-de-contagem" },
    { nome: "Figuras Planas 2º Ano", slug: "figuras-planas-2ano" },
    { nome: "Gráfico Frutas", slug: "grafico-frutas" },
    { nome: "Gráficos E Tabelas 2º Ano", slug: "graficos-e-tabelas-2ano" },
    { nome: "Horas E Meia Hora", slug: "horas-e-meia-hora" },
    { nome: "Introdução Ao Dinheiro 2º Ano", slug: "introducao-ao-dinheiro-2ano" },
    { nome: "Introdução As Frações 2º Ano", slug: "introducao-as-fracoes-2ano" },
    { nome: "Introdução Multiplicação Divisão", slug: "introducao-multiplicacao-divisao" },
    { nome: "Lógica Inicial 2º Ano", slug: "logica-inicial-2-ano" },
    { nome: "Medidas Básicas 2º Ano", slug: "medidas-basicas-2ano" },
    { nome: "Medidas De Capacidade 2º Ano", slug: "medidas-de-capacidade-2-ano" },
    { nome: "Mundo Das Formas", slug: "mundo-das-formas" },
    { nome: "Mundo Das Horas", slug: "mundo-das-horas" },
    { nome: "Números 101 A 200", slug: "numeros-101-a-200" },
    { nome: "Números Ate 100", slug: "numeros-ate-100" },
    { nome: "Operações Problemas 2º Ano", slug: "operacoes-problemas-2ano" },
    { nome: "Posição E Espaço 2º Ano", slug: "posicao-e-espaco-2ano" },
    { nome: "Problemas Simples 2º Ano", slug: "problemas-simples-2ano" },
    { nome: "Problemas Soma", slug: "problemas-soma" },
    { nome: "Problemas Subtração 2º Ano", slug: "problemas-subtracao-2ano" },
    { nome: "Quebra- Cabeça Contas 2º Ano", slug: "quebra-cabeca-contas-2-ano" },
    { nome: "Quebra- Cabeça Contas 2º Ano 2", slug: "quebra-cabeca-contas-2-ano-2" },
    { nome: "Quebra- Cabeça Contass 2º Ano 3", slug: "quebra-cabeca-contass-2-ano-3" },
    { nome: "Sequência Numerica 2º Ano", slug: "sequencia-numerica-2-ano" },
    { nome: "Sequencias Multiplas", slug: "sequencias-multiplas" },
    { nome: "Sistema Monetário Mercadinho", slug: "sistema-monetario-mercadinho" },
    { nome: "Soma 2º Ano", slug: "soma-2-ano" },
    { nome: "Subtração 2º Ano", slug: "subtracao-2-ano" }
];
